name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run:  npm install
        working-directory: kukukonnect
      - name: Run tests
        run: npm test
        working-directory: kukukonnect
      - name: Build project
        run: npm run build
        working-directory: kukukonnect
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --confirm --token $VERCEL_TOKEN
        working-directory: kukukonnect

